#!/bin/sh

set -e

touch /tmp/input.json
source_params=$(jq -r '.source' < /tmp/input.json)

repository_url=$(echo "$source_params" | jq -r '.repository_url')
username=$(echo "$source_params" | jq -r '.username')
password=$(echo "$source_params" | jq -r '.password')
auth_header=$(curl -s -u "$username:$password" -X POST "$repository_url/service/rest/v1/session" | jq -r '.data.authToken')

artifacts=$(curl -s -H "Authorization: Bearer $auth_header" "$repository_url/service/rest/v1/search" | jq -r '.items[] | .name')

