#!/bin/sh

set -e

cat > /tmp/input.json
source_params=$(jq -r '.source' < /tmp/input.json)
params=$(jq -r '.params' < /tmp/input.json)
artifact_path=$(jq -r '.artifact_path' < /tmp/input.json)


repository_url=$(jq -r '.source.repository_url' < /tmp/input.json)
username=$(jq -r '.source.username' < /tmp/input.json)
password=$(jq -r '.source.password' < /tmp/input.json)

curl -u "$username:$password" --upload-file "$artifact_path" "$repository_url"
