#!/bin/sh

set -e

cat > /tmp/input.json
source_params=$(jq -r '.source' < /tmp/input.json)
params=$(jq -r '.params' < /tmp/input.json)
artifact_path=$(jq -r '.artifact_path' < /tmp/input.json)


repository_url=$(echo "$source_params" | jq -r '.repository_url')
username=$(echo "$source_params" | jq -r '.username')
password=$(echo "$source_params" | jq -r '.password')

curl -u "$username:$password" --upload-file "$artifact_path" "$repository_url"
